# Generated by Django 5.0.6 on 2024-06-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoriosProducto',
            fields=[
                ('idAccProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nomAccProducto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horaFin', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('idLocal', models.AutoField(primary_key=True, serialize=False)),
                ('nomLocal', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('idCancha', models.AutoField(primary_key=True, serialize=False)),
                ('nomCancha', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('idLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.local')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('idReservaCancha', models.AutoField(primary_key=True, serialize=False)),
                ('fechRegistro', models.DateField(auto_now_add=True)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idAccProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alquiler.accesoriosproducto')),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.horario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('idDetalleReserva', models.AutoField(primary_key=True, serialize=False)),
                ('idCancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.cancha')),
                ('idReservaCancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.reservacancha')),
            ],
        ),
    ]
