# Generated by Django 5.0.6 on 2024-05-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativa',
            options={'verbose_name_plural': 'Administrativas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='administrativa',
            old_name='munDocumento',
            new_name='numDocumento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='munDocumento',
            new_name='numDocumento',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
