# Generated by Django 5.0.6 on 2024-05-29 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0002_alter_administrativa_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrativa',
            old_name='idAdministrativa',
            new_name='idPersona',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='idCliente',
            new_name='idPersona',
        ),
    ]
