# Generated by Django 5.0.6 on 2024-06-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0003_rename_idadministrativa_administrativa_idpersona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horaFin', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='caja',
            name='idAdministrativa',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='idAdministrativa',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='idLocal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='idCaja',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='idCaja',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idAccProducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idLocal',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='idProducto',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='idCliente',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='idLocal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='idLocal',
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('idCancha', models.AutoField(primary_key=True, serialize=False)),
                ('nomCancha', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='canchas/')),
                ('idLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.local')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('idReservaCancha', models.AutoField(primary_key=True, serialize=False)),
                ('fechRegistro', models.DateField()),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField()),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idAccProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.accesoriosproducto')),
                ('idCancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.cancha')),
                ('idHorario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.horario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('idDetalleReserva', models.AutoField(primary_key=True, serialize=False)),
                ('idCancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.cancha')),
                ('idReservaCancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alquiler.reservacancha')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='idReservaCancha',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Alquiler.reservacancha'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Administrativa',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
